services:
  postgresql:
    container_name: postgresql
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data

  app:
    container_name: tgms
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql/tgms_db
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SERVER_PORT=8087
    ports:
      - "8087:8087"
    expose:
      - "8087"
    depends_on:
      - postgresql
    restart: always

volumes:
  db-data:
