CREATE DATABASE tgms_db;
create table if not exists person
(
    id int generated by default as identity primary key,
    full_name varchar(100) not null unique,
    email varchar(100) unique,
    role varchar(100) not null,
    description varchar(300),
    year_of_birth date,
    password varchar(100),
    chief_id int
    );
create table if not exists task
(
    id int generated by default as identity primary key,
    task_name varchar(200) not null,
    priority int not null,
    status boolean not null,
    created_at timestamp,
    deadline timestamp,
    execution_at timestamp,
    person_id int references person(id) on delete set null,
    description varchar(300),
    report varchar(300)
    );